[package]
name = "object-store-hedging"
description = "Read request hedging for object-store"
authors = ["SpiralDB Authors <hello@spiraldb.com>"]
repository = "https://github.com/spiraldb/object-store-hedging"
readme = "README.md"
keywords = ["object", "storage", "cloud"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"
include = ["src/**/*.rs", "LICENSE-MIT", "LICENSE-APACHE", "Cargo.toml"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = "0.3.31"
object_store = { version = "0.13.1", default-features = false }
parking_lot = "0.12.5"
sketches-ddsketch = "0.3.0"
tokio = { version = "1.49.0", features = ["time"], default-features = false }

[dev-dependencies]
rstest = "0.18"
